uns_radius=0.25;
sacia_normal_search_radius=2.5;
sacia_fpfh_search_radius=5.0;
sacia_number_samples=3.0;
sacia_min_sample_distance=10.0;
sacia_max_correspondence_distance=1.0;
sacia_maximum_iterations=5000.0;
sacia_correspondence_randomness=500.0;
icp_maximum_iterations=1000;
icp_max_correspondence_distance=5;
icp_transformation_epsilon=1e-10;
icp_euclidean_fitness_epsilon=1e-10;