uns_radius=1;
sacia_normal_search_radius=3.0;
sacia_fpfh_search_radius=10.0;
sacia_number_samples=3;
sacia_min_sample_distance=10.0;
sacia_max_correspondence_distance=1;
sacia_maximum_iterations=2000;
sacia_correspondence_randomness=200;
icp_maximum_iterations=1000;
icp_max_correspondence_distance=5.0;
icp_transformation_epsilon=1e-10;
icp_euclidean_fitness_epsilon=1e-10;