#!/bin/bash

git clone https://github.com/FENGSim/FENGSim.git

cd FENGSim

git clone https://github.com/FENGSim/docs.git
git clone https://github.com/FENGSim/fengsim.github.io.git

cd toolkit

git clone https://github.com/FENGSim/MultiX.git
git clone https://github.com/FENGSim/CFD.git
git clone https://github.com/FENGSim/CEM.git
git clone https://github.com/FENGSim/DAE.git
git clone https://github.com/FENGSim/NLA.git
git clone https://github.com/FENGSim/Particles.git
git clone https://github.com/FENGSim/PS.git

# report
cd MultiX/docs
./install

cd ../../../../

echo "compression begin"
echo "compression begin" > download_log.txt

tar -zcf FENGSim_$(date +%Y_%m_%d).tar.gz FENGSim

current_time=$(date)
echo "compression end ${current_time}" > download_log.txt
echo "compression end ${current_time}"
