#!/bin/bash

git clone https://github.com/fengsim/FENGSim.git

cd FENGSim

git clone https://github.com/fengsim/docs.git

cd toolkit

git clone https://github.com/fengsim/MultiX.git
git clone https://github.com/fengsim/CFD.git
git clone https://github.com/fengsim/CEM.git
git clone https://github.com/fengsim/DAE.git
git clone https://github.com/fengsim/NLA.git
git clone https://github.com/fengsim/Particles.git
git clone https://github.com/fengsim/PS.git

# report
cd MultiX/docs
./install

cd ../../../../

echo "compression begin"
echo "compression begin" > download_log.txt

tar -zcf FENGSim_$(date +%Y_%m_%d).tar.gz FENGSim

current_time=$(date)
echo "compression end ${current_time}" > download_log.txt
echo "compression end ${current_time}"
