#!/bin/bash

sudo docker rm test

fengsim="$(realpath ${BASH_SOURCE[0]%"$(basename "$0")"}/../)"

IMAGE_NAME="ubuntu:24.04"
#IMAGE_NAME="ros2:latest"

sudo xhost +si:localuser:root

#xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f /tmp/.docker.xauth nmerge -

sudo chmod 777 /tmp/.docker.xauth

XAUTH=/tmp/.docker.xauth

sudo docker run --name test -it --privileged --network host \
    --shm-size=5G \
    -w /home/test \
    -v $fengsim:/home/test/FENGSim \
    -e DISPLAY=$DISPLAY \
    -v $XAUTH:$XAUTH -e XAUTHORITY=$XAUTH \
    -v /tmp/.X11-unix/:/tmp/.X11-unix \
    -e OMPI_ALLOW_RUN_AS_ROOT=1 \
    -e OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1 \
    $IMAGE_NAME /bin/bash
