#!/bin/bash

if ! dpkg -s jq &> /dev/null; then
    sudo apt-get update
    sudo apt-get install -y jq
fi

fengsim="$(realpath ${BASH_SOURCE[0]%"$(basename "$0")"}/../../)"
echo "fengsim: "$fengsim
depfile="${fengsim}/cli/src/dep.json"
echo "depfile: "$depfile

tool_install() {
    tool_dir="$fengsim/$(jq -r ".${1}.dir" "$depfile")" # -r remove "" and must use "" can't use ''
    echo "tool_dir: "$tool_dir
    tool_install="$fengsim/cli/src/${1}"
    echo "tool_install: "$tool_install
    (cd $tool_dir && . $tool_install)
}

function_name() {
    deps=($(jq -r ".${1}.dep[]" "$depfile"))
    for dep in "${deps[@]}"; do
	function_name "$dep"
    done
    echo "${1}"
    tool_install "${1}"
}

function_name "${1}"
