#!/bin/sh

# need to install petsc first

export PETSC_DIR=$PWD/../petsc-3.23
export PETSC_ARCH=arch-linux-c-debug
./configure --prefix=$PWD/../install/slepc
make SLEPC_DIR=$PWD PETSC_DIR=$PWD/../petsc-3.23 PETSC_ARCH=arch-linux-c-debug
make SLEPC_DIR=$PWD PETSC_DIR=$PWD/../petsc-3.23 install
make SLEPC_DIR=$PWD PETSC_DIR=$PWD/../petsc-3.23 PETSC_ARCH=arch-linux-c-debug check
